---

services:
  api:
    image: phatnguyen1812/supersentaidle-api
    container_name: supersentaidle_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - docker.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - supersentaidle_api
    restart: always
networks:
  supersentaidle_api:
    driver: bridge
