// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Character struct {
	ID               int64
	SeriesID         sql.NullInt64
	Name             string
	RangerColor      sql.NullString
	Role             sql.NullString
	CivilianIdentity sql.NullString
	SignatureMove    sql.NullString
	ImageUrl         sql.NullString
}

type DailyChallenge struct {
	ID       int64
	Date     time.Time
	Category string
	AnswerID int64
}

type Mecha struct {
	ID         int64
	SeriesID   sql.NullInt64
	Name       string
	Type       sql.NullString
	Components sql.NullString
	ImageUrl   sql.NullString
}

type Series struct {
	ID          int64
	Name        string
	Year        int32
	Theme       sql.NullString
	ColorScheme sql.NullString
	ImageUrl    sql.NullString
}

type UserProgress struct {
	ID             int64
	UserID         int64
	ChallengeID    sql.NullInt64
	Attempts       int32
	Completed      bool
	CompletionTime sql.NullTime
}

type Weapon struct {
	ID        int64
	SeriesID  sql.NullInt64
	Name      string
	Type      sql.NullString
	WielderID sql.NullInt64
	ImageUrl  sql.NullString
}
