//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Series struct {
	ID          int64 `sql:"primary_key"`
	Name        string
	Year        int32
	Theme       *string
	ColorScheme *string
	ImageURL    *string
}
